# Generated by Django 4.1.5 on 2023-01-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(choices=[('lombax', 'Lombax'), ('robot', 'Robot'), ('unknown', 'Unknown')], max_length=255)),
                ('appearances', models.ManyToManyField(to='games.game')),
            ],
        ),
    ]
