# Generated by Django 4.1.5 on 2023-01-19 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('characters', '0003_alter_character_first_appearance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('appearances', models.ManyToManyField(to='games.game')),
                ('characters', models.ManyToManyField(to='characters.character')),
                ('first_appearance', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planet_debuted', to='games.game')),
            ],
        ),
    ]
